version: 2

models:
  - name: dim_listings_cleansed
    description: Cleansed table which contains Airbnb listings.
    data_tests:
      - minimum_row_count:
          arguments:
            min_row_count: 1000
          config:
            severity: error
    columns:
      - name: listing_id
        description: Primary key for the listing.
        data_tests:
          - unique
          - not_null

      - name: host_id
        description: The host's id. References the host table.
        data_tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_hosts_cleansed')
                field: host_id

      - name: room_type
        description: Type of the apartment / room
        data_tests:
          - accepted_values:
              arguments:
                values: ['Entire home/apt', 'Private room', 'Shared room', 'Hotel room']
      - name: minimum_nights
        description: '{{ doc("dim_listing_cleansed__minimum_nights") }}'
        data_tests:
          - positive_values

  - name: dim_hosts_cleansed
    description: Cleansed table which contains Airbnb hosts.
    config:
      contract:
        enforced: true
    columns:
      - name: host_id
        data_type: integer
      - name: host_name
        data_type: string
      - name: is_superhost
        data_type: string
      - name: updated_at
        data_type: timestamp
      - name: created_at
        data_type: timestamp
  - name: dim_listings_w_hosts
    tests:
      - dbt_expectations.expect_table_row_count_to_equal_other_table:
          compare_model: source('airbnb', 'listings')
          ## group_by: [col1, col2] # (Optional)
          ## compare_group_by: [col1, col2] # (Optional)
          ## factor: 1 # (Optional)
          ## row_condition: "id is not null" # (Optional)
          ## compare_row_condition: "id is not null" # (Optional)
    columns:
      - name: price
        tests:
          - dbt_expectations.expect_column_quantile_values_to_be_between:
              quantile: .99
              min_value: 50 # (Optional)
              max_value: 500 # (Optional)
              ## group_by: [group_id, other_group_id, ...] # (Optional)
              ## row_condition: "id is not null" # (Optional)
              ## strictly: false # (Optional. Default is 'false'. Adds an 'or equal to' to the comparison operator for min/max)
          - dbt_expectations.expect_column_max_to_be_between:
              ## min_value: 1 # (Optional)
              max_value: 5000 # (Optional)
              config:
                severity: warn
              ## group_by: [group_id, other_group_id, ...] # (Optional)
              ## row_condition: "id is not null" # (Optional)
              ## strictly: false # (Optional. Default is 'false'. Adds an 'or equal to' to the comparison operator for min/max)

